# -*- coding: utf-8 -*-
# Copyright 2026 Morwi Encoders Consulting SA de CV
# License LGPL-3.0 or later (https://www.gnu.org/licenses/lgpl.html).
"""Fix the Studio-customized sale.order / purchase.order QWeb reports for
Odoo 19, mirroring the account.move fixes in migrations/2.0.2.

These reports are `ir.ui.view` records generated by Odoo Studio, not files
tracked in this repo. They still contained several patterns removed/renamed
by Odoo 19:

- `sale.order.line.product_uom` / `purchase.order.line.product_uom` renamed
  to `product_uom_id`: some Studio duplicates read `line.product_uom.name`
  directly as a python attribute (not through `t-field`), which raises
  ``AttributeError`` since the ORM has no python-level alias for a removed
  field.
- `purchase.order.notes` renamed to `note` ("Terms and Conditions"):
  `t-field="o.notes"` raises a ``KeyError`` in `ir_qweb._get_field`.
- `account.move.line.display_type` used to be ``False``/empty for a regular
  line; Odoo 19 sets it to ``'product'``. Eleven sale.order document
  templates and one purchase.order document template guarded their line
  row with ``t-if="not line.display_type"``, always false now, so orders
  printed with an empty product table.
- `account.document_tax_totals_copy_7` / `_copy_8` (used by two Studio
  sale.order report variants) still read the pre-Odoo-17 tax_totals shape
  (`formatted_amount`, `groups_by_subtotal`) instead of the current
  `subtotals` / `tax_groups` shape, raising a ``KeyError`` on the totals
  block.
- the "Odoo Studio: report_purchaseorder_document copy(1) customization"
  overlay (inherited view on top of
  ``purchase.report_purchaseorder_document_copy_1``) has its own
  `line.product_uom.name` and `o.notes` occurrences that need the same fix.
"""

from odoo import api, SUPERUSER_ID

DISPLAY_TYPE_VIEW_KEYS = [
    "sale.report_saleorder_document_copy_1_copy_1",
    "sale.report_saleorder_document_copy_1_copy_1_copy_2",
    "sale.report_saleorder_document_copy_1_copy_1_copy_2_copy_1",
    "sale.report_saleorder_document_copy_1_copy_1_copy_2_copy_1_copy_1",
    "sale.report_saleorder_document_copy_1_copy_1_copy_2_copy_1_copy_1_copy_1",
    "sale.report_saleorder_document_copy_1_copy_2",
    "sale.report_saleorder_document_copy_1_copy_2_copy_1",
    "sale.report_saleorder_document_copy_1_copy_2_copy_2",
    "sale.report_saleorder_document_copy_1_copy_2_copy_3",
    "sale.report_saleorder_document_copy_1_copy_2_copy_3_copy_1",
    "sale.report_saleorder_document_copy_1_copy_2_copy_3_copy_2",
    "purchase.report_purchaseorder_document",
]

PRODUCT_UOM_VIEW_KEYS = [
    "sale.report_saleorder_document_copy_1_copy_1",
    "sale.report_saleorder_document_copy_1_copy_1_copy_2",
    "sale.report_saleorder_document_copy_1_copy_1_copy_2_copy_1",
    "sale.report_saleorder_document_copy_1_copy_1_copy_2_copy_1_copy_1",
    "sale.report_saleorder_document_copy_1_copy_1_copy_2_copy_1_copy_1_copy_1",
    "sale.report_saleorder_document_copy_1_copy_2",
    "sale.report_saleorder_document_copy_1_copy_2_copy_1",
    "sale.report_saleorder_document_copy_1_copy_2_copy_2",
    "sale.report_saleorder_document_copy_1_copy_2_copy_3",
    "sale.report_saleorder_document_copy_1_copy_2_copy_3_copy_1",
    "sale.report_saleorder_document_copy_1_copy_2_copy_3_copy_2",
    "purchase.report_purchaseorder_document_copy_1",
    "purchase.report_purchaseorder_document_copy_1_copy_1",
    "purchase.report_purchaseorder_document_copy_1_copy_2",
    "purchase.report_purchaseorder_document_copy_1_copy_2_copy_4",
    "purchase.report_purchaseorder_document_copy_1_copy_2_copy_5",
    "purchase.report_purchaseorder_document_copy_1_copy_3",
    "purchase.report_purchaseorder_document_copy_1_copy_3_copy_1",
]

NOTES_VIEW_KEYS = [
    "purchase.report_purchaseorder_document_copy_1",
    "purchase.report_purchaseorder_document_copy_1_copy_1",
    "purchase.report_purchaseorder_document_copy_1_copy_3",
    "purchase.report_purchaseorder_document_copy_1_copy_3_copy_1",
]

TAX_TOTALS_TEMPLATE = '''<t t-name="{name}">
            <!--
                Generic template to display tax totals in pdf reports.
                Used by invoices, SO and PO.

                ARGUMENTS:
                - tax_totals: dict in the form generated by account.move's _get_tax_totals.
            -->
            <t t-set="same_tax_base" t-value="tax_totals['same_tax_base']"/>
            <t t-foreach="tax_totals['subtotals']" t-as="subtotal">
                <tr class="border-black o_subtotal">
                    <td><strong t-esc="subtotal['name']"/></td>

                    <td class="text-end">
                        <span t-att-class="oe_subtotal_footer_separator" t-out="subtotal['base_amount_currency']" t-options="{{'widget': 'monetary', 'display_currency': currency}}"/>
                    </td>
                </tr>
                <t t-set="total_discount" t-value="0"/>
                <t t-if="o">
                    <t t-set="lines" t-value="o.invoice_line_ids"/>
                </t>
                <t t-if="doc">
                    <t t-set="lines" t-value="doc.order_line"/>
                </t>
                <t t-foreach="lines" t-as="line">
                    <t t-if="o">
                        <t t-set="quantity" t-value="line.quantity"/>
                    </t>
                    <t t-if="doc">
                        <t t-set="quantity" t-value="line.product_uom_qty"/>
                    </t>
                    <t t-set="line_discount_price_unit" t-value="line.price_unit * (line.discount / 100.0)"/>
                    <t t-set="line_discount" t-value="quantity * line_discount_price_unit"/>
                    <t t-set="total_discount" t-value="total_discount + line_discount"/>
                </t>
                <tr t-if="total_discount" class="border-black o_subtotal">
                    <td><strong>Descuento</strong></td>

                    <td class="text-end">
                        <span t-att-class="oe_subtotal_footer_separator" t-esc="round(total_discount, 2)" t-options="{{&quot;widget&quot;: &quot;monetary&quot;, &quot;display_currency&quot;: currency}}"/>
                    </td>
                </tr>

                <t t-foreach="subtotal['tax_groups']" t-as="tax_group">
                    <tr class="o_taxes">
                        <t t-if="same_tax_base or tax_group['display_base_amount_currency'] is False">
                            <td style="max-width: 200px;">
                                <span t-out="tax_group['group_name']"/>
                            </td>
                            <td class="text-end o_price_total">
                                <span class="text-nowrap" t-out="tax_group['tax_amount_currency']" t-options="{{'widget': 'monetary', 'display_currency': currency}}"/>
                            </td>
                        </t>
                        <t t-else="">
                            <td>
                                <span t-out="tax_group['group_name']"/>
                                <span> on </span>
                                <span class="text-nowrap" t-out="tax_group['display_base_amount_currency']" t-options="{{'widget': 'monetary', 'display_currency': currency}}"/>
                            </td>
                            <td class="text-end o_price_total">
                                <span class="text-nowrap" t-out="tax_group['tax_amount_currency']" t-options="{{'widget': 'monetary', 'display_currency': currency}}"/>
                            </td>
                        </t>
                    </tr>
                </t>
            </t>

            <!--Total amount with all taxes-->
            <tr class="border-black o_total">
                <td><strong>Total</strong></td>
                <td class="text-end">
                    <span t-out="tax_totals['total_amount_currency']" t-options="{{'widget': 'monetary', 'display_currency': currency}}"/>
                </td>
            </tr>
        </t>'''

TAX_TOTALS_TEMPLATES_TO_REWRITE = [
    "account.document_tax_totals_copy_7",
    "account.document_tax_totals_copy_8",
]


def _get_view(env, key):
    return env["ir.ui.view"].search([("key", "=", key)], limit=1)


def migrate(cr, version):
    env = api.Environment(cr, SUPERUSER_ID, {})

    for key in set(DISPLAY_TYPE_VIEW_KEYS + PRODUCT_UOM_VIEW_KEYS + NOTES_VIEW_KEYS):
        view = _get_view(env, key)
        if not view:
            continue
        arch = view.arch

        if key in DISPLAY_TYPE_VIEW_KEYS:
            arch = arch.replace(
                't-if="not line.display_type"',
                "t-if=\"line.display_type == 'product' or not line.display_type\"",
            )
        if key in PRODUCT_UOM_VIEW_KEYS:
            arch = arch.replace("line.product_uom.name", "line.product_uom_id.name")
            arch = arch.replace("line.product_uom\"", "line.product_uom_id\"")
        if key in NOTES_VIEW_KEYS:
            arch = arch.replace('t-field="o.notes"', 't-field="o.note"')

        if arch != view.arch:
            view.write({"arch": arch})

    for key in TAX_TOTALS_TEMPLATES_TO_REWRITE:
        view = _get_view(env, key)
        if view:
            new_arch = TAX_TOTALS_TEMPLATE.format(name=key)
            if view.arch != new_arch:
                view.write({"arch": new_arch})

    _fix_purchaseorder_copy_1_overlay(env)


def _fix_purchaseorder_copy_1_overlay(env):
    """Fix `line.product_uom.name` and `o.notes` in the Studio overlay on
    top of `purchase.report_purchaseorder_document_copy_1`."""
    parent = _get_view(env, "purchase.report_purchaseorder_document_copy_1")
    if not parent:
        return
    overlay = env["ir.ui.view"].search([
        ("inherit_id", "=", parent.id),
        ("name", "like", "Odoo Studio:"),
    ], limit=1)
    if not overlay:
        return
    arch = overlay.arch
    arch = arch.replace("line.product_uom.name", "line.product_uom_id.name")
    arch = arch.replace('t-field="o.notes"', 't-field="o.note"')
    if arch != overlay.arch:
        overlay.write({"arch": arch})
